/**
 * Fingerspelling classifier.
 *
 * Matches live MediaPipe hand landmarks against canonical pose templates
 * generated by the parametric hand model — no training data required.
 *
 * Pipeline per frame:
 *   1. normalise landmarks (wrist at origin, scaled by palm size)
 *   2. weighted nearest-template distance (fingertips and thumb weigh more,
 *      z is down-weighted because MediaPipe depth is noisy)
 *   3. both chiralities are tried (left/right hand, mirrored cameras)
 *
 * `Smoother` turns noisy per-frame results into stable, committed letters.
 */

import { handLandmarks, toMediaPipe } from "./hand-model.js";
import { LETTER_POSES, STATIC_LETTERS } from "./poses.js";

const TIPS = new Set([4, 8, 12, 16, 20]);
const THUMB_IDX = new Set([1, 2, 3, 4]);

const WEIGHTS = Array.from({ length: 21 }, (_, i) => {
  let w = 1.0;
  if (TIPS.has(i)) w *= 2.2;
  if (THUMB_IDX.has(i)) w *= 1.5;
  return w;
});
const WSUM = WEIGHTS.reduce((a, b) => a + b, 0);
const Z_WEIGHT = 0.35; // MediaPipe z is approximate

/** Wrist → origin, scale by mean wrist→knuckle distance. Keeps orientation. */
export function normalize(lms, mirrorX = false) {
  const w = lms[0];
  const knuckles = [5, 9, 13, 17];
  let scale = 0;
  for (const k of knuckles) {
    scale += Math.hypot(lms[k].x - w.x, lms[k].y - w.y, (lms[k].z || 0) - (w.z || 0));
  }
  scale = scale / knuckles.length || 1e-6;
  const sx = mirrorX ? -1 : 1;
  return lms.map((p) => [
    (sx * (p.x - w.x)) / scale,
    (p.y - w.y) / scale,
    ((p.z || 0) - (w.z || 0)) / scale,
  ]);
}

function distance(a, b) {
  let sum = 0;
  for (let i = 0; i < 21; i++) {
    const dx = a[i][0] - b[i][0];
    const dy = a[i][1] - b[i][1];
    const dz = a[i][2] - b[i][2];
    sum += WEIGHTS[i] * (dx * dx + dy * dy + Z_WEIGHT * dz * dz);
  }
  return Math.sqrt(sum / WSUM);
}

// Build templates once at module load.
const TEMPLATES = STATIC_LETTERS.map((letter) => ({
  letter,
  norm: normalize(toMediaPipe(handLandmarks(LETTER_POSES[letter]))),
}));

/**
 * Classify one frame of MediaPipe landmarks.
 * Returns ranked candidates: [{letter, dist, score}], best first.
 * score is a softmax-style confidence in (0, 1].
 */
export function classify(lms) {
  if (!lms || lms.length !== 21) return [];
  const variants = [normalize(lms, false), normalize(lms, true)];
  const best = new Map();
  for (const v of variants) {
    for (const t of TEMPLATES) {
      const d = distance(v, t.norm);
      const prev = best.get(t.letter);
      if (prev === undefined || d < prev) best.set(t.letter, d);
    }
  }
  const ranked = [...best.entries()]
    .map(([letter, dist]) => ({ letter, dist }))
    .sort((a, b) => a.dist - b.dist);
  const tau = 0.12;
  let zsum = 0;
  for (const r of ranked) zsum += Math.exp(-r.dist / tau);
  for (const r of ranked) r.score = Math.exp(-r.dist / tau) / zsum;
  return ranked;
}

/** Frames whose best match is farther than this are treated as "no letter". */
export const MAX_DIST = 0.55;

/**
 * Temporal smoothing: a letter is "stable" once it has dominated the recent
 * window; it is "committed" (emitted) after being held for `holdMs`.
 * Keeping the same letter held commits it again after `holdMs * repeatFactor`,
 * so double letters ("LL" in HELLO) can be spelled without dropping the hand.
 */
export class Smoother {
  constructor({ window = 12, minShare = 0.65, holdMs = 700, repeatFactor = 2 } = {}) {
    this.window = window;
    this.minShare = minShare;
    this.holdMs = holdMs;
    this.repeatFactor = repeatFactor;
    this.frames = [];
    this.stable = null;
    this.stableSince = 0;
    this.commitCount = 0;
  }

  reset() {
    this.frames = [];
    this.stable = null;
    this.commitCount = 0;
  }

  /**
   * Feed one frame's top candidate (or null when no hand / too far).
   * Returns {stable, progress, committed} where `committed` is a letter
   * exactly once per successful hold, else null.
   */
  push(letter, now = performance.now()) {
    this.frames.push(letter);
    if (this.frames.length > this.window) this.frames.shift();

    const counts = new Map();
    for (const f of this.frames) {
      if (f) counts.set(f, (counts.get(f) || 0) + 1);
    }
    let top = null;
    let topCount = 0;
    for (const [l, c] of counts) {
      if (c > topCount) {
        top = l;
        topCount = c;
      }
    }
    const share = topCount / this.window;
    const newStable = share >= this.minShare ? top : null;

    if (newStable !== this.stable) {
      this.stable = newStable;
      this.stableSince = now;
      this.commitCount = 0;
    }

    let committed = null;
    let progress = 0;
    if (this.stable) {
      const need =
        this.commitCount === 0 ? this.holdMs : this.holdMs * this.repeatFactor;
      progress = Math.min(1, (now - this.stableSince) / need);
      if (progress >= 1) {
        committed = this.stable;
        this.commitCount++;
        this.stableSince = now; // restart the hold for a possible repeat
      }
    }
    return { stable: this.stable, progress, committed };
  }
}
